name: Code Quality (C)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.c'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
  workflow_dispatch:

jobs:
  lint:
    name: Lint C Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cppcheck and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck curl

      - name: Run Cppcheck and Generate XML Report
        run: |
          # Run cppcheck on the C code files and output to an XML file
          cppcheck --enable=all --inconclusive --xml . 2> cppcheck-report.xml || true

          # Check if the XML report is empty
          if [ ! -s cppcheck-report.xml ]; then
            echo "Cppcheck report is empty. No issues found." >> cppcheck-report.xml
          fi

      - name: Generate HTML Report from XML using cppcheck-htmlreport
        run: |
          # Generate an HTML report from the cppcheck XML file using cppcheck-htmlreport
          cppcheck-htmlreport --file=cppcheck-report.xml --title=LibreOffice --report-dir=cppcheck_reports --source-dir=. || true

      - name: Upload Cppcheck HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: Cppcheck_HTML_Report
          path: cppcheck_reports/*.html
