name: Code Quality (C)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.c'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
  workflow_dispatch:

jobs:
  lint:
    name: Analyze C Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck clang clang-format xsltproc

      - name: Generate Combined HTML Report
        run: |
          # Create output directory
          mkdir -p reports

          # Run Cppcheck and generate XML report
          cppcheck --enable=all --inconclusive --xml . 2> reports/cppcheck-report.xml || true
          # Convert XML to HTML using XSLT
          xsltproc /usr/share/cppcheck/cppcheck-htmlreport.xsl reports/cppcheck-report.xml > reports/cppcheck-report.html || true

          # Run Clang-Tidy on each C file and save output to a text file
          echo "<h2>Clang-Tidy Analysis</h2>" > reports/clang-tidy-report.html
          for file in $(find . -name '*.c'); do
            echo "<h3>File: $file</h3><pre>" >> reports/clang-tidy-report.html
            clang-tidy "$file" -- >> reports/clang-tidy-report.html || true
            echo "</pre>" >> reports/clang-tidy-report.html
          done

          # Run Clang-Format on each C file and save formatted code
          echo "<h2>Clang-Format Output</h2>" > reports/clang-format-report.html
          mkdir -p formatted_code
          for file in $(find . -name '*.c'); do
            formatted_file="formatted_code/$(basename "$file")"
            clang-format "$file" > "$formatted_file"
            echo "<h3>File: $(basename "$file")</h3><pre>" >> reports/clang-format-report.html
            cat "$formatted_file" >> reports/clang-format-report.html
            echo "</pre>" >> reports/clang-format-report.html
          done

          # Combine all reports into a single HTML
          echo "<html><head><title>Code Quality Report</title></head><body>" > reports/combined-report.html
          echo "<h1>Code Quality Report</h1>" >> reports/combined-report.html
          echo "<h2>Cppcheck Analysis</h2>" >> reports/combined-report.html
          cat reports/cppcheck-report.html >> reports/combined-report.html
          cat reports/clang-tidy-report.html >> reports/combined-report.html
          cat reports/clang-format-report.html >> reports/combined-report.html
          echo "</body></html>" >> reports/combined-report.html

      - name: Upload Combined HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: C_Code_Quality_Report
          path: reports/combined-report.html
