name: Code Quality (C)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.c'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
  workflow_dispatch:

jobs:
  lint:
    name: Lint C Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cppcheck and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck xsltproc

      - name: Run Cppcheck and Generate Reports
        run: |
          # Run Cppcheck and save XML output
          cppcheck --enable=all --inconclusive --xml . 2> cppcheck-report.xml || true

          # Convert XML to HTML using XSLT
          xsltproc /usr/share/cppcheck/cppcheck-htmlreport.xsl cppcheck-report.xml > cppcheck-report.html || true

      - name: Upload Cppcheck HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: Cppcheck_HTML_Report
          path: cppcheck-report.html
