name: Code Coverage (C)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.c'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
  workflow_dispatch:

jobs:
  test:
    name: Run Tests and Generate HTML Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y lcov gcovr gcc

      - name: Compile all .c files with coverage flags
        run: |
          # Compile all .c files in the root directory with coverage flags
          for file in $(find . -maxdepth 1 -name "*.c"); do
            gcc -fprofile-arcs -ftest-coverage -c "$file"
          done

          # Link all .o files to create the test executable
          gcc -fprofile-arcs -ftest-coverage -o test_executable *.o

      - name: Run tests
        run: ./test_executable

      - name: Generate HTML coverage report using gcovr
        run: |
          # Generate the HTML coverage report
          gcovr --html --html-details -o coverage.html

      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: c_coverage_html_report
          path: coverage.html

      - name: Clean up coverage files
        run: rm -rf *.gcov *.gcda *.gcno *.o test_executable coverage.html
