name: Code Coverage (JS)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.js'

jobs:
  coverage:
    name: Calculate Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Tests and Calculate Coverage
        id: coverage
        run: |
          # Run tests with coverage
          npx jest --coverage
          
          # Extract coverage percentage from coverage-summary.json
          COVERAGE_PERCENT=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
          echo "COVERAGE_PERCENT=$COVERAGE_PERCENT" >> $GITHUB_ENV
          echo "Coverage Percentage: $COVERAGE_PERCENT%"

      - name: Save Coverage to Database
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          # Save coverage percentage to database
          curl -X POST -H "Content-Type: application/json" -d '{
            "file": "example.js",
            "metric": "coverage",
            "value": "'$COVERAGE_PERCENT'"
          }' $DB_CONNECTION_STRING
